<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Sasidhar" failures="1" tests="4" name="LoginTests" time="56.176" errors="0" timestamp="2025-08-31T18:11:00 IST">
  <testcase classname="com.saucedemo.tests.LoginTest_with_TestNG" name="loginTest" time="6.723"/>
  <testcase classname="com.saucedemo.tests.LoginTest_with_TestNG" name="loginTest" time="25.687">
    <failure type="java.lang.AssertionError" message="Login failed for locked_out_user : secret_sauce | Error: Epic sadface: Sorry, this user has been locked out.">
      <![CDATA[java.lang.AssertionError: Login failed for locked_out_user : secret_sauce | Error: Epic sadface: Sorry, this user has been locked out.
at com.saucedemo.tests.LoginTest_with_TestNG.loginTest(LoginTest_with_TestNG.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.saucedemo.tests.LoginTest_with_TestNG" name="loginTest" time="6.676"/>
  <testcase classname="com.saucedemo.tests.LoginTest_with_TestNG" name="loginTest" time="12.796"/>
</testsuite> <!-- LoginTests -->
